### ISSUE TITLE
Instance creation is doing an rbd import from local disk

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#543] opened 2015-04-13 19:52 UTC
I caught `nova-compute` running an `rbd import` of an image off local disk rather than issuing an O(1) copy:

```
ubuntu@bcpc-vm2:~$ ps -ef | grep rbd
nova     36679 35982 10 15:40 ?        00:00:05 rbd import --pool images /var/lib/nova/instances/_base/c48fe80b84775b19ab2f6cc29712e426c1bee725 f6d8101c-84fd-4fcf-8b88-d70e80d8b9e2_disk --new-format --id admin --conf /etc/ceph/ceph.conf
ubuntu@bcpc-vm2:~$ ls -lh /var/lib/nova/instances/_base/c48fe80b84775b19ab2f6cc29712e426c1bee725 
-rw-r--r-- 1 nova nova 3.0G Apr 13 15:40 /var/lib/nova/instances/_base//c48fe80b84775b19ab2f6cc29712e426c1bee725
```

This isn't expected behavior - it should be loading in from Glance and as an O(1) copy.

**Comment by erhudy** [comment] 2015-06-24 14:56
I couldn't reproduce this with a RAW image on current 5.3.0. Launched instance with **Boot from image** and watched process list; brief activity from `glance-api` and then the image launched. I didn't see `rbd` running anywhere.

**Comment by erhudy** [comment] 2015-06-26 19:26
Closing issue because I wasn't able to reproduce and everything seems to be behaving as desired. (Possibly fixed by other Ceph changes from @cloudm2 / @kelvk ).

**Closed by erhudy** 2015-06-26 19:26 UTC
Labels: Ceph, OpenStack
