### ISSUE TITLE
Add option to compact LevelDB on startup 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#397] opened 2014-11-26 14:53 UTC
I've seen monitor stores get crazy large (10GBs). You can instruct a monitor to compact on startup (see wiki). We should have this as an environment option so it can be rolled by a cloud operator in with a temp change to environment rather than a change to code.

**Comment by dsvua** [comment] 2017-05-10 18:11
Duplicate of #435

**Closed** 2019-06-06 21:13 UTC
Labels: Ceph, Enhancement
